[package]
name = "insa-auth"
version = "0.1.0"
edition = "2021"

[dependencies]
jsonwebtoken = "9"
rocket = "0.5.0"
serde = {version = "1.0", features = ["derive"] }
serde_json = "1.0"
urlencoding = "2.1.3"
isahc = "1.7"
string-tools = "0.1.0"
chrono = "0.4.38"
rand = "0.8"
